const USER_ACTIVE_META_KEY = 'UserActiveMetaKey';
const USER_INACTIVE_PERMANENTLY_META_KEY = 'UserInactivePermanentlyMetaKey';
const USER_BLOCKED_META_KEY = 'UserBlockedMetaKey';

export {
    USER_ACTIVE_META_KEY,
    USER_BLOCKED_META_KEY,
    USER_INACTIVE_PERMANENTLY_META_KEY,
};
